[package]
name = "freivalds"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = { workspace = true }
bls = { workspace = true }
nalgebra = "0.31.0"
rand = { version = "0.8.5", features = ["std_rng"] }
