[package]
name = "freivalds-algorithm"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bls12-381 = "0.3.0"
ark-ff = "0.3.0"
nalgebra = "0.31.0"
rand = { version = "0.8.5", features = ["std_rng"] }
